In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("infectious_disease_epmc.csv")

In [4]:
df.head()

,DOI,Title,Abstract,FullText,Source
0,10.1186/s13071-025-06826-8,Dynamics of vector competence for dengue virus...,NaN,NaN,EuropePMC
1,10.1186/s13071-025-06829-5,First detection of tick-borne encephalitis vir...,NaN,NaN,EuropePMC
2,10.1186/s13071-025-06841-9,Investigations on the occurrence of West Nile ...,NaN,NaN,EuropePMC
3,10.1186/s13071-025-06727-w,Association between greenspace morphology and ...,NaN,NaN,EuropePMC
4,10.1186/s13071-025-06663-9,Exploiting venom toxins in paratransgenesis to...,NaN,NaN,EuropePMC

In [5]:
df.describe()

       Abstract  FullText
count       0.0       0.0
mean        NaN       NaN
std         NaN       NaN
min         NaN       NaN
25%         NaN       NaN
50%         NaN       NaN
75%         NaN       NaN
max         NaN       NaN